alpha-pool:
  port: 10000
  servers:
    - host: localhost
      port: 6379
      priority: 1
      failure_limit: 3
    - host: localhost
      port: 7777
      failure_limit: 2
beta-pool:
  port: 10001
  servers:
    - host: localhost
      port: 6379
      priority: 1
      failure_limit: 1