alpha-pool:
  port: 10000
  servers:
    - host: localhost
      port: 6379
      priority: 1
      failure_limit: 3
      healthcheck_milliseconds: 120
      connection-pool-size: 40
    - host: localhost
      port: 7777
      failure_limit: 2
      healthcheck_milliseconds: 120
      connection-pool-size: 40
beta-pool:
  port: 10001
  servers:
    - host: localhost
      port: 6379
      priority: 1
      failure_limit: 1
      healthcheck_milliseconds: 180
      connection-pool-size: 40